// Code generated by Kitex v0.6.1. DO NOT EDIT.

package cservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	service "kitexSvr-serviceC/kitex_gen/kitex/service"
)

func serviceInfo() *kitex.ServiceInfo {
	return cServiceServiceInfo
}

var cServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "CService"
	handlerType := (*service.CService)(nil)
	methods := map[string]kitex.MethodInfo{
		"requestA": kitex.NewMethodInfo(requestAHandler, newCServiceRequestAArgs, newCServiceRequestAResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "service",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func requestAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*service.CServiceRequestAArgs)
	realResult := result.(*service.CServiceRequestAResult)
	success, err := handler.(service.CService).RequestA(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCServiceRequestAArgs() interface{} {
	return service.NewCServiceRequestAArgs()
}

func newCServiceRequestAResult() interface{} {
	return service.NewCServiceRequestAResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RequestA(ctx context.Context, req *service.CReq) (r *service.CResp, err error) {
	var _args service.CServiceRequestAArgs
	_args.Req = req
	var _result service.CServiceRequestAResult
	if err = p.c.Call(ctx, "requestA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
