// Code generated by hertz generator.

package service

import (
	"context"
	"hertzSvr/biz/handler/hertzSvr/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	service "hertzSvr/biz/model/hertzSvr/service"
)

// RequestC .
// @router /C/req [POST]
func RequestC(ctx context.Context, c *app.RequestContext) {
	var err error
	var req service.CReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if clientInfo.name != "CService" {
		clientInfo.name = "CService"
		clientInfo.cli = utils.NewClient(clientInfo.name, provider, resolver)
	}

	resp := utils.GetHTTPGenericResponse(ctx, c, "RequestC", clientInfo.cli)

	c.JSON(consts.StatusOK, resp)
}
