// Code generated by hertz generator.

package service

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"hertzSvr/biz/model/hertzSvr/service"
)

// Request .
// @router /request [POST]
func Request(ctx context.Context, c *app.RequestContext) {
	var err error
	var req service.SvrRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(service.SvrResponse)

	c.JSON(consts.StatusOK, resp)
}

// RegisterIDL .
// @router /registerIDL [POST]
func RegisterIDL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req service.RegisterIDL
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(service.SvrResponse)

	c.JSON(consts.StatusOK, resp)
}
