// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	hertzSvr_idlManager "hertzSvr-Gateway/biz/router/hertzSvr/idlManager"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	hertzSvr_idlManager.Register(r)
}
