// Code generated by Kitex v0.6.1. DO NOT EDIT.

package dservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	service "kitexSvr-serviceD/kitex_gen/kitex/service"
)

func serviceInfo() *kitex.ServiceInfo {
	return dServiceServiceInfo
}

var dServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "DService"
	handlerType := (*service.DService)(nil)
	methods := map[string]kitex.MethodInfo{
		"RequestD": kitex.NewMethodInfo(requestDHandler, newDServiceRequestDArgs, newDServiceRequestDResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "service",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func requestDHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*service.DServiceRequestDArgs)
	realResult := result.(*service.DServiceRequestDResult)
	success, err := handler.(service.DService).RequestD(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDServiceRequestDArgs() interface{} {
	return service.NewDServiceRequestDArgs()
}

func newDServiceRequestDResult() interface{} {
	return service.NewDServiceRequestDResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RequestD(ctx context.Context, req *service.DReq) (r *service.DResp, err error) {
	var _args service.DServiceRequestDArgs
	_args.Req = req
	var _result service.DServiceRequestDResult
	if err = p.c.Call(ctx, "RequestD", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
