// Code generated by Kitex v0.6.1. DO NOT EDIT.

package advancedcalservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	service "kitexSvr-AdvancedCalService/kitex_gen/kitex/service"
)

func serviceInfo() *kitex.ServiceInfo {
	return advancedCalServiceServiceInfo
}

var advancedCalServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "AdvancedCalService"
	handlerType := (*service.AdvancedCalService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Fact": kitex.NewMethodInfo(factHandler, newAdvancedCalServiceFactArgs, newAdvancedCalServiceFactResult, false),
		"Fib":  kitex.NewMethodInfo(fibHandler, newAdvancedCalServiceFibArgs, newAdvancedCalServiceFibResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "service",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func factHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*service.AdvancedCalServiceFactArgs)
	realResult := result.(*service.AdvancedCalServiceFactResult)
	success, err := handler.(service.AdvancedCalService).Fact(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvancedCalServiceFactArgs() interface{} {
	return service.NewAdvancedCalServiceFactArgs()
}

func newAdvancedCalServiceFactResult() interface{} {
	return service.NewAdvancedCalServiceFactResult()
}

func fibHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*service.AdvancedCalServiceFibArgs)
	realResult := result.(*service.AdvancedCalServiceFibResult)
	success, err := handler.(service.AdvancedCalService).Fib(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvancedCalServiceFibArgs() interface{} {
	return service.NewAdvancedCalServiceFibArgs()
}

func newAdvancedCalServiceFibResult() interface{} {
	return service.NewAdvancedCalServiceFibResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Fact(ctx context.Context, request *service.Request) (r *service.Response, err error) {
	var _args service.AdvancedCalServiceFactArgs
	_args.Request = request
	var _result service.AdvancedCalServiceFactResult
	if err = p.c.Call(ctx, "Fact", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Fib(ctx context.Context, request *service.Request) (r *service.Response, err error) {
	var _args service.AdvancedCalServiceFibArgs
	_args.Request = request
	var _result service.AdvancedCalServiceFibResult
	if err = p.c.Call(ctx, "Fib", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
