// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "hertzSvr/biz/handler"
	"hertzSvr/biz/handler/hertzSvr/service"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.POST("/gateway/:svc/:method", service.Gateway)
	// your code ...
}
