// Code generated by Kitex v0.6.1. DO NOT EDIT.

package aservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	service "kitexSvr-serviceA/kitex_gen/kitex/service"
)

func serviceInfo() *kitex.ServiceInfo {
	return aServiceServiceInfo
}

var aServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "AService"
	handlerType := (*service.AService)(nil)
	methods := map[string]kitex.MethodInfo{
		"requestA": kitex.NewMethodInfo(requestAHandler, newAServiceRequestAArgs, newAServiceRequestAResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "service",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func requestAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*service.AServiceRequestAArgs)
	realResult := result.(*service.AServiceRequestAResult)
	success, err := handler.(service.AService).RequestA(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAServiceRequestAArgs() interface{} {
	return service.NewAServiceRequestAArgs()
}

func newAServiceRequestAResult() interface{} {
	return service.NewAServiceRequestAResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RequestA(ctx context.Context, req *service.AReq) (r *service.AResp, err error) {
	var _args service.AServiceRequestAArgs
	_args.Req = req
	var _result service.AServiceRequestAResult
	if err = p.c.Call(ctx, "requestA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
