// Code generated by hertz generator.

package service

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	service "hertzSvr-IDLManagement/biz/model/hertzSvr/service"
)

// AddIDL .
// 添加IDL,如果添加的服务已经存在,则拒绝添加,并返回错误信息
// @router /idlManager/add [POST]
func AddIDL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req service.IDLInfo
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(service.IDLResponse)

	var svrInfo IDLMessage
	//判断是否已经存在服务
	DB.First(&svrInfo, "svc_name = ?", req.Name)
	if svrInfo.ID != 0 {
		resp.Success = false
		resp.Message = "ERROR:SERVICE ALREADY EXISTED"
		c.JSON(consts.StatusOK, resp)
		return
	}
	//向数据库添加IDL
	DB.Create(&IDLMessage{
		SvcName: req.Name,
		IDL:     req.Idl,
	})
	resp.Success = true
	resp.Message = "SUCCESS ADD"
	c.JSON(consts.StatusOK, resp)
}

// DeleteIDL .
// 删除IDL,如果数据库中不存在则返回错误信息
// @router /idlManager/delete [POST]
func DeleteIDL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req service.IDLMessage
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(service.IDLResponse)
	var svrInfo IDLMessage
	//判断是否已经存在服务
	DB.First(&svrInfo, "svc_name = ?", req.Name)
	if svrInfo.ID == 0 {
		resp.Success = false
		resp.Message = "ERROR:NO SUCH SERVICE"
		c.JSON(consts.StatusOK, resp)
		return
	}
	//删除IDL
	DB.Delete(&svrInfo, svrInfo.ID)
	resp.Success = true
	resp.Message = "SUCCESS DELETE"
	c.JSON(consts.StatusOK, resp)
}

// UpdateIDL .
// 更新IDL,如果服务不存在则返回错误信息
// @router /idlManager/update [POST]
func UpdateIDL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req service.IDLInfo
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(service.IDLResponse)

	var svrInfo IDLMessage
	//判断是否已经存在服务
	DB.First(&svrInfo, "svc_name = ?", req.Name)
	if svrInfo.ID == 0 {
		resp.Success = false
		resp.Message = "ERROR:NO SUCH SERVICE"
		c.JSON(consts.StatusOK, resp)
		return
	}
	//更新IDL
	DB.Model(&svrInfo).Update("id_l", req.Idl)

	resp.Success = true
	resp.Message = "SUCCESS DELETE"

	c.JSON(consts.StatusOK, resp)
}

// QueryIDL .
// 查询IDL,若服务存在则返回IDL,否则返回错误信息.注意错误信息保存在response.Idl中
// @router /idlManager/query [GET]
func QueryIDL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req service.IDLQueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(service.IDLInfo)

	var svrInfo IDLMessage
	//判断服务是否存在
	DB.First(&svrInfo, "svc_name = ?", req.Name)
	if svrInfo.ID == 0 {
		resp.Idl = "ERROR:NO SUCH SERVICE"
		resp.Name = req.Name
		c.JSON(consts.StatusOK, resp)
		return
	}
	// 返回IDL
	resp = &service.IDLInfo{
		Name: req.Name,
		Idl:  svrInfo.IDL,
	}

	c.JSON(consts.StatusOK, resp)
}
