// Code generated by Kitex v0.6.1. DO NOT EDIT.

package bservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	service "kitexSvr-serviceB/kitex_gen/kitex/service"
)

func serviceInfo() *kitex.ServiceInfo {
	return bServiceServiceInfo
}

var bServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "BService"
	handlerType := (*service.BService)(nil)
	methods := map[string]kitex.MethodInfo{
		"RequestB": kitex.NewMethodInfo(requestBHandler, newBServiceRequestBArgs, newBServiceRequestBResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "service",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func requestBHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*service.BServiceRequestBArgs)
	realResult := result.(*service.BServiceRequestBResult)
	success, err := handler.(service.BService).RequestB(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBServiceRequestBArgs() interface{} {
	return service.NewBServiceRequestBArgs()
}

func newBServiceRequestBResult() interface{} {
	return service.NewBServiceRequestBResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RequestB(ctx context.Context, req *service.BReq) (r *service.BResp, err error) {
	var _args service.BServiceRequestBArgs
	_args.Req = req
	var _result service.BServiceRequestBResult
	if err = p.c.Call(ctx, "RequestB", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
